name: "Debug with ssh (forked by LazuliKao)"
description: "This GitHub Action enables direct interaction with the host system running your GitHub Actions via SSH"
author: "Owen Ou"
branding:
  icon: "terminal"
  color: "purple"
runs:
  using: "node20"
  main: "lib/index.js"
inputs:
  limit-access-to-actor:
    description: "If only the public SSH keys of the user triggering the workflow should be authorized"
    required: false
    default: "false"
  limit-access-to-users:
    description: "If only the public SSH keys of the listed GitHub users should be authorized"
    required: false
    default: ""
  authorized-keys:
    description: "SSH public key(s) to authorize for access (text content, not file path). Multiple keys can be separated by newlines."
    required: false
    default: ""
  upterm-server:
    description: "upterm server address (required), supported protocols are ssh, ws, or wss."
    required: true
    default: "ssh://uptermd.upterm.dev:22"
  wait-timeout-minutes:
    description: "Integer number of minutes to wait for user to connect before shutting down server. Once a user connects, the server will stay up."
    required: false
    default: ""
  hide-client-ip:
    description: "Hide client IP addresses from output."
    required: false
    default: "false"
  force-command:
    description: "Enforce a specified command for clients to join, and link the command's input/output to the client's terminal."
    required: false
    default: ""
